config/routes.rb
Rails.application.routes.draw do
  ####### This part MUST precede any other lines!!
  #filter :extension #, :exclude => %r(^admin/)
  filter :locale#,    :exclude => /^\/admin/
  default_url_options(locale: I18n.locale) if Rails.env.test?  # manually defined in application_controller.rb
  ####### Up to here

  resources :diagnose, only: [:index]
  resources :urls
  resources :domains
  resources :domain_titles
  resources :site_categories
  resources :channels
  namespace :channels do
    resources :fetch_youtube_channels, only: [:update]  # may add :create in future
  end
  resources :channel_owners
  namespace :channel_owners do
    get 'create_with_artists/new'
  end
  resources :channel_types
  resources :channel_platforms
  resources :harami_vid_music_assocs, only: [:destroy]
  namespace :harami_vid_music_assocs do
    resources :timings, only: [:show, :edit, :update]
    resources :notes,   only: [:show, :edit, :update]
  end
  resources :artist_music_plays, only: [:destroy]
  namespace :artist_music_plays do
    resources :edit_multis, only: [:index, :edit, :update, :create, :show]
  end
  resources :instruments
  resources :play_roles
  namespace :events do
    resources :align_start_time_with_vid, only: [:show, :update]
  end
  resources :event_items
  namespace :event_items do
    resources :nominal_machine_titles, only: [:show, :update]
    resources :match_parents,     only: [:update]
    resources :deep_duplicates,   only: [:create]
    resources :destroy_with_amps, only: [:destroy]
    resources :resettle_new_events, only: [:update]
  end
  resources :harami1129_reviews
  resources :event_groups
  resources :model_summaries
  namespace :translations do  # "update" is used so that it can be handled with Ability
    get ':id/promotes/update', to: 'promotes#update', as: :update_promotes # => translations_update_promote_path(:id) => /translations/:id/promotes/update
    get ':id/demotes/update',  to: 'demotes#update',  as: :update_demotes  # => translations_update_demote_path(:id)  => /translations/:id/demotes/update
  end
  namespace :artists do
    resources :ac_titles, only: [:index]
    get    ':id/merges/new',  to: 'merges#new',     as: :new_merges  # => artists_new_merge_path(:id)  => /artists/:id/merges/new
    get    ':id/merges/edit', to: 'merges#edit',    as: :edit_merges # => artists_edit_merge_path(:id) => /artists/:id/merges/edit
    match  ':id/merges',      to: 'merges#update',  as: :update_merges, via: [:put, :patch]
    namespace :merges do
      get 'artist_with_ids',   to: 'artist_with_ids#index'  # => artists_merges_artist_with_ids_path => /artists/merges/artist_with_ids#index
    end
  end
  resources :page_formats

  resources :static_pages
  resources :country_masters
  namespace :country_masters do
    post   ':id/create_countries',  to: 'create_countries#update', as: :create_countries  # => country_masters_create_countries_path(:id)  => /country_masters/:id/create_countries
  end

  namespace :musics do
    resources :ac_titles, only: [:index]  # changed from: get 'ac_titles/index'
    get    ':id/merges/new',  to: 'merges#new',     as: :new_merges  # => musics_new_merge_path(:id)  => /musics/:id/merges/new
    get    ':id/merges/edit', to: 'merges#edit',    as: :edit_merges # => musics_edit_merge_path(:id) => /musics/:id/merges/edit
    match  ':id/merges',      to: 'merges#update',  as: :update_merges, via: [:put, :patch]
    resources :upload_music_csvs, only: [:create]
    namespace :merges do
      get 'music_with_ids',   to: 'music_with_ids#index'  # => musics_merges_music_with_ids_path => /musics/merges/music_with_ids#index
    end
  end
  resources :engage_multi_hows, only: [:index, :show, :edit, :create]
  resources :engages, only: [:index, :show, :new, :create, :destroy]
  resources :engage_hows
  #get 'user_role_assoc/update'
  resources :user_role_assoc, only: :update
  namespace :users do
    resources :edit_roles, only: [:update]
    ##resource :confirm, only: :update
    #resources :confirm, only: :update
    match  ':id/confirms', to: 'confirms#update', as: :confirm, via: [:put, :patch]
    get    ':id/deactivate_users/edit', to: 'deactivate_users#edit',    as: :edit_deactivate_users # => users_edit_deactivate_users_path(:id) => /users/:id/deactivate_users/edit
    match  ':id/deactivate_users',      to: 'deactivate_users#update',  as: :do_deactivate_users, via: [:put, :patch]
    delete ':id/deactivate_users',      to: 'deactivate_users#destroy', as: :destroy_deactivate_users  # NOTE: without "as", the prefix would be "users"
  end

  get 'users/index'
  resources :harami1129s
  resources :harami1129s do
    resource :populate,            only: [:update], module: 'harami1129s'
    resource :internal_insertions, only: [:update], module: 'harami1129s'
  end
  namespace :harami1129s do
    resource :download_harami1129s, only: [:new]
    resource :inject_from_harami1129s, only: [:create]
    post     :internal_insertions, to: 'internal_insertions#update_all'
    #patch     :internal_insertions, to: 'internal_insertions#update_all'
    #put       :internal_insertions, to: 'internal_insertions#update_all'  # Patch and Put does not work: Rails.application.routes.recognize_path("/harami1129s/internal_insertions", method: :put) #=> {:controller=>"harami1129s", :action=>"update", :id=>"internal_insertions"}
  end
  resources :harami_vids do
    resource :upload_hvma_csv, only: [:create], controller: 'harami_vids/upload_hvma_csvs'
    # => POST   /harami_vids/:harami_vid_id/upload_hvma_csvs
    #   params are like: params[:harami_vid_id] and params[:upload_hvma_csv][:filename]
    # NOte: "resources :upload_hvma_csvs" (note the plural) would do virtually the same, but "resource" is semantically cleaner.
  end
  namespace :harami_vids do
    resources :fetch_youtube_data, only: [:create, :update]
    resources :update_places,      only: [:show,   :update]
    resources :add_missing_music_to_evits, only: [:show,   :update]
  end
  resources :genres
  resources :translations
  resources :places
  resources :prefectures
  resources :countries
  resources :roles
  resources :role_categories
  resources :sexes

  ## WARNING: It seems the following MUST come after namespace definitions (of :artists and :musics, specifically).  Otherwise, auto-completion would not work...
  %w(artists events harami_vids musics places).each do |model_plural|
    resources model_plural.to_sym do
      resources :anchorings, controller: model_plural+'/anchorings'
    end
  end

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  # devise_for :users  # Default
  devise_for :users, :except => [:destroy]
  # devise_for :users, :path_prefix => 'd'  # => /usrs/d/sign_up etc
  resources :users, :only =>[:show]
  #match '/users/:id',     to: 'users#show',       via: 'get'
  #match '/users/:id',     to: 'users#show',  :as => :user,     via: 'get'
  root to: "home#index"
  get 'home/index'

  match '/users',   to: 'users#index',   via: 'get'
  ##resources :users do
  ##  resource :user_lists, only: [:index], module: 'users'
  ##end
  #namespace :users do
  #  get      :user_lists, only: [:index], to: 'user_lists#index'
  #  post     :user_lists, only: [:index], to: 'user_lists#index'
  #end

  # Arbitrary page paths are dealt with StaticPagePublicsController
  get '/static_page_publics', to: 'static_page_publics#index'
  constraints(lambda { |request| !File.basename(request.fullpath).sub(/\?.*/, '').include?('.') }) do
    # Except the filenames with a suffix like .jpg or even .html
    get '*path', to: 'static_page_publics#show'
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/engage_multi_hows_controller.rb
# Controllers to edit/delete/add a set of existing {Engage}s
# for a pair of {Artist} and {Music} with multiple {EngageHow}s
class EngageMultiHowsController < ApplicationController
  include ModuleCommon # for split_hash_with_keys

  before_action :set_engages, only: %i( index )  # Unusual, but for index only.
  load_and_authorize_resource :engage

  # GET parameters of {Artist} and {Music} IDs are mandatory.
  def index
  end

  def show
    edit
  end

  def edit
    engage = Engage.find(params[:id])
    # redirect_to engage_multi_hows_path(request.parameters.merge({artist_id: engage.artist_id, music_id: engage.music_id}))
    redirect_to engage_multi_hows_path(artist_id: engage.artist_id, music_id: engage.music_id)
  end

  def create
    # Parameters: {"authenticity_token"=>"[FILTERED]", "engage"=>{"year_20"=>"", "contribution_20"=>"", "note_20"=>"", "to_destroy_20"=>"true", "engage_how"=>["", "9", "7"], "year"=>"", "contribution"=>"", "note"=>"", "artist_id"=>"3", "music_id"=>"10"}, "commit"=>"Submit"}
    # NOTE: if the checkbox is not checked, the key "to_destroy_20" does NOT exist.
    params.require([:engage])
    params.permit!

    to_destroy = 'to_destroy'
    raise 'Contac the code developer' if !Engage.method_defined?(to_destroy.to_sym)

    # Hash newhs for those for to-be-added Engages, and resths for existing Engages
    newhs, resths = split_hash_with_keys(params[:engage], %w(artist_id music_id engage_how year contribution note))
    hs_existent = {}
    resths.each_pair do |k,v|
      next if (/^(year|contribution|note|#{Regexp.quote to_destroy})_(\d+)/ !~ k)
      eid = $2.to_i
      hs_existent[eid] = {} if !hs_existent.key? eid
      hs_existent[eid][$1] = 
        if $1 == to_destroy
          helpers.get_bool_from_params(v)
        else
          (v.blank? ? nil : v)  # If blank, replaced with nil.
        end
    end

    n_updated = 0
    n_destroyed = 0
    n_new = 0
    begin
      ActiveRecord::Base.transaction(requires_new: true) do
        # Creates (multiple) Engages if specified
        hs, hsprm = split_hash_with_keys(newhs, ['engage_how'])
        hsprm.select!{|k,v| !v.blank?}
        specified_engage_hows = hs['engage_how'].map{|i| i.blank? ? nil : i}.compact
        specified_engage_hows.each do |engage_how_id|
          Engage.create! hsprm.merge({engage_how_id: engage_how_id})
          n_new += 1
        end

        # sanity (security) check
        engages = {}
        hs_existent.each_pair do |eid, ea_prms|
          engages[eid] = engage = Engage.find(eid)
          next if !engage # This could happen if Engage is destroyed independently and simultaneously by someone unrelated.
          if engage.artist_id != newhs['artist_id'].to_i || engage.music_id !=newhs['music_id'].to_i
            # Should never happen except for malicious attacks.
            raise "Unrelated Engage is specified! ID=#{engage.id}"
          end
        end

        # destroys some existing records (Note new ones, if any, have been already created).
        ids_to_destroy = hs_existent.map{|ek, eh| eh.key?(to_destroy) && eh[to_destroy] && ek || nil}.compact
        n_destroyed = destroy_engages(engages, ids_to_destroy, newhs)

        # Removes the to_destroy key from the Hash (to be used in update!)
        hs_existent.each_value{|eh|
          eh.delete(to_destroy) if eh.key?(to_destroy)
        }

        # edits existing records
        hs_existent.each_pair do |eid, ea_prms|
          engage = engages[eid] || next  # "next" if it is destroyed by someone else simultaneously.
          next if ids_to_destroy.include? eid  # already destroyed.

          engage.update!(ea_prms)
          if engage.saved_changes?
            n_updated += 1
            msg = sprintf "(%s#%s) Engage(ID=%s) updated by User(ID=%s): saved_changes=%s", self.class.name, __method__, eid, current_user.id, engage.saved_changes.inspect
            logger.debug msg
          end
        end
      end
    rescue => err
      ## Transaction or processing failed.
      msg = sprintf "(%s#%s) Engages failed to be updated by User(ID=%s) with error: %s", self.class.name, __method__, current_user.id, err.message
      logger.debug msg
      if /Unrelated Engage/ =~ msg
        logger.error msg
        raise
      end
      set_engages if !defined?(@engage) || !defined?(@engages)  # to set @engage etc
      @engage.errors.add :base, err.message
    end

    # Note @engage always exists because of load_and_authorize_resource
    # though it is nil unless explicitly reset by set_engages(), which
    # is called when encountering an error.
    if @engage && @engage.errors.present?
      respond_to do |format|
        format.html { render :index, status: :unprocessable_content }  # A bit unusual, but render :index
        format.json { render json: @engage.errors, status: :unprocessable_content }
      end
    else
      respond_to do |format|
        msg = sprintf "Updated %d, destroyed %d, and created %d Engages successfully.", n_updated, n_destroyed, n_new
        format.html { redirect_to engage_multi_hows_path(artist_id: newhs['artist_id'], music_id: newhs['music_id']), success: msg } # "success" defined in /app/controllers/application_controller.rb
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_engages
      #params.require([:artist_id, :music_id]) # when called second time after create! fails, the params is params[:engage][:artist_id]
      params.permit!
      hskwd = {}
      %i(engage_how_id year contribution note).each do |ek|
        hskwd[ek] = params[ek] if params[ek]
      end

      @music  = Music.find( params[:music_id]  || params[:engage][:music_id])
      @artist = Artist.find(params[:artist_id] || params[:engage][:artist_id])
      @engages = Engage.where(artist: @artist, music: @music).joins(:engage_how).order('engage_hows.weight')
      @engage  = Engage.new(  artist: @artist, music: @music, year: @music.year, **hskwd)
      @engage_others = (@engages.exists? ? @engages.first : @engage).with_the_other_artists
    end

    ## Only allow a list of trusted parameters through. create only (NOT update)
    #def engage_params
    #  params.require(:engage).permit(:contribution, :year, :artist_id, :engage_how_id, :music_id, :note)
    #end

    # Destory specified Engages, providing it satisfies certain conditions;
    # i.e., either dependent Harami1129s do not exist or there are alternative
    # Engages that can be assigned to those dependent Harami1129s.
    #
    # @param engages [Hash] id => Engage for the same Artist and Music
    # @param ids_to_destroy [Array] of id-s to destroy
    # @param newhs [Hash] taken from params, containing artist_id and music_id (String or Integer)
    # @return [Integer] Number of the destroyed records.
    def destroy_engages(engages, ids_to_destroy, newhs)
      return 0 if ids_to_destroy.empty?

      all_music_engages = Engage.where(music: newhs['music_id'])  # Same Music, any Artists
      all_this_engages  = all_music_engages.where(artist_id: newhs['artist_id']) # Same Music&Artist
      harami1129s = Harami1129.joins(:engage).where('engage_id IN (?)', all_this_engages.pluck(:id)).distinct
      if harami1129s.count > 0 && ids_to_destroy.size >= all_music_engages.count
        set_engages if !defined?(@engage) || !defined?(@engages)  # to set @engage etc
        msg = 'Cannot destroy all Engages about this Music when a dependent Harami1129 exists.'
        @engage.errors.add :to_destroy, msg
        raise ActiveRecord::Rollback, 'Rollback because: '+msg
warn "ERROR:This should be never executed.... rollback"
      end

      # Build a Relation to get a new Engage ID to assign to the existing Harami1129s
      all_this_ids = all_this_engages.pluck :id
      if all_this_ids.all?{|i| ids_to_destroy.include? i}
        # Harami1129#engage_id will be assigned to an Enage with a different Artist
        rela = all_music_engages.where.not(artist_id: newhs['artist_id'])
      else
        # Harami1129#engage_id will be assigned to an Enage with the same Artist with a different EngageHow
        rela = all_this_engages.where.not('engages.id IN (?)', ids_to_destroy)
      end

      # Update Harami1129#engage_id for *all* related Harami1129s.
      # Note that even if the related Engage for a Harami1129 is not destroyed,
      # if one of the Engages is destroyed, the Harami1129#engage_id may be
      # updated. For example,
      #
      #   a_harami1129.engage  # => (AI, Story, How(Composer))
      #   engage(AI, Story, How(Unknown)).destroy
      #   a_harami1129.engage  # => (AI, Story, How(Singer_Original))
      #
      # This should not matter because the whole purpose of a Harami1129 having
      # a related Engage is just a convenient way to point both an Artist and Music
      # and therefore EngageHow (or year) is irrelevant.
      harami1129s.each do |h1129|
        engage = rela.joins(:engage_how).order('engage_hows.weight').first
        raise 'Contact the code developer. engage should never be nil here' if !engage
        h1129.engage = engage
        h1129.save!
      end

      n_destroyed = 0
      # Destroy Engages
      ids_to_destroy.each do |idd|
        if engages[idd]
          engages[idd].destroy
          n_destroyed += 1
        end
      end
      return n_destroyed
    end
end

app/helpers/engage_multi_hows_helper.rb
module EngageMultiHowsHelper
end

app/views/engage_multi_hows/create.html.erb
<h1>EngageMultiHows#create</h1>
<p>Find me in app/views/engage_multi_hows/create.html.erb</p>

app/views/engage_multi_hows/index.html.erb
<p id="notice"><%= notice %></p>

<%= render partial: 'layouts/form_print_errors', locals: {model: @engage} %>

<% artist_title = @artist.title_or_alt %>
<% music_name = @music.title_or_alt %>
<h1>Engages for Music=(<%= link_to music_name, @music %>) by <%= link_to artist_title, @artist %></h1>

<% n_engages = @engages.count %>
<% n_engage_others = @engage_others.count %>
<% n_cols = (current_user.sysadmin? ? 10 : 9) %>
<% val_klasses = { year: 'input_year', contribution: 'input_float' } %>

<%= simple_form_for @engage, url: engage_multi_hows_url do |form| %>
  <%= form.hidden_field :artist_id, :value => @artist.id %>
  <%= form.hidden_field :music_id,  :value => @music.id %>
  <table style="border: none;">
    <thead>
      <tr>
        <th>ID</th>
        <th>Artist</th>
        <th>How?</th>
        <th>Year</th>
        <th>Contribution</th>
        <th>Note</th>
        <th title="Number of associations to Harami1129"># Harami1129s</th>
        <th title="Check this (or these) and submit to destroy (or replace) the record. Note if a dependent (=NumLinks) exists and when an Engage(s) is deleted, the association will be replaced with another one.">Destroy</th>
        <th>Engage</th>
        <% if current_user.sysadmin? %>
        <th></th>
        <% end %>
      </tr>
    </thead>
  
    <tbody>
      <% @engages.each do |engage| %>
        <tr>
          <td><%= engage.id %></td>
          <td><%= artist_title %></td>
          <td><%= engage_how = engage.engage_how; link_to engage_how.title_or_alt(langcode: I18n.locale), engage_how %></td>
          <% %i(year contribution note).each do |kwd| %>
            <% hs_klass = ((:note != kwd.to_sym) ? { class: val_klasses[kwd.to_sym] } : {}) %>
            <td><%= form.input kwd, label: false, required: false, input_html: {id: ['engage', kwd, engage.id].join('_'), name: sprintf('engage[%s_%d]', kwd.to_s, engage.id), value: engage.send(kwd)}.merge(hs_klass) %></td>
          <% end %>
          <td><%= engage.harami1129s.count %>
            <% if can? :read, Harami1129 %>
              (<%= engage.harami1129s.map.with_index{|h, i| link_to i+1, harami1129_path(h)+'#harami1129_show_Engage', title: sprintf('ID=%d', h.id)}.join(', ').html_safe %>)
            <% end %>
          </td>
          <td class="checkbox_destroy">
              <% kwd = :to_destroy %>
              <%= form.input kwd, label: false, required: false, as: :boolean, checked_value: true, unchecked_value: false, checked: false, input_html: {id: ['engage', kwd, engage.id].join('_'), name: sprintf('engage[%s_%d]', kwd.to_s, engage.id)} %>
          </td>
          <td><%= link_to 'Show', engage %></td>
          <% if current_user.sysadmin? %>
          <td>
            <% if engage.harami1129s.exists? && (n_engages + n_engage_others > 1) %>
              <% msg = 'Will be replaced with another one of '+((n_engages > 0) ? 'this' : 'another')+'Artist' %>
              <%# This msg can be used (thougt not yet implmented) like:  "title: msg" %>
              <%= link_to 'Destroy(Admin-only)', engage, method: :delete, url: engage_url(engage), data: { confirm: t('are_you_sure') } %>
            <% else %>
              <span title="Cannot be destroyed because this entry has a dependent Harami1129(s) and there are no other Engages.">Destroy(Admin-only)</span>
            <% end %>
          </td>
          <% end %>
        </tr>
      <% end %>

      <tr>
        <th colspan="<%= n_cols %>"><strong>New engagement (if any)</strong></th>
      </tr>
      <tr>
        <td>NEW</td>
        <td><%= artist_title %></td>
        <td><%= form.input :engage_how, label: 'EngageHow(複数可)', collection: EngageHow.all.order(:weight).map{|i| [i.title_or_alt(langcode: I18n.locale, str_fallback: "NONE"), i.id]}, required: false, prompt: "Please select", input_html: { multiple: true } %></td>
        <td><%= form.input :year, required: false, input_html: { class: val_klasses[:year] } %></td>
        <td><%= form.input :contribution, label: 'Contribution(0.0-1.0)', required: false, input_html: { class:  val_klasses[:contribution] } %></td>
        <td><%= form.input :note, input_html: { 'rows' => 4 } %></td>
        <td colspan="<%= n_cols-6 %>"></td>
      </tr>
    </tbody>
  </table>
  <%= form.submit t("layouts.submit_button")%>
<% end %>
  
  <table style="border: none; margin-left: 1em;">
    <thead>
      <tr>
        <th>ID</th>
        <th>Artist</th>
        <th>How?</th>
        <th>Year</th>
        <th>Contribution</th>
        <th>Note</th>
        <th title="Number of associations to Harami1129">NumLinks</th>
        <th title="Check this (or these) and submit to destroy (or replace) the record. Note if a dependent (=NumLinks) exists and when an Engage(s) is deleted, the association will be replaced with another one.">Destroy</th>
        <th>Engage</th>
        <% if current_user.sysadmin? %>
        <th></th>
        <% end %>
      </tr>
    </thead>
  
      <tr>
        <th colspan="<%= n_cols %>"><strong>Engages for Music by other artists</strong></th>
      </tr>
      <% @engage_others.each do |engage| %>
        <tr>
          <td><%= engage.id %></td>
          <td><%= link_to engage.artist.title_or_alt, engage.artist %></td>
          <td><%= engage_how = engage.engage_how; link_to engage_how.title_or_alt(langcode: I18n.locale), engage_how %></td>
          <td><%= engage.year ? engage.year : '&mdash;'.html_safe %></td>
          <td><%= engage.contribution ? engage.contribution : '&mdash;'.html_safe %></td>
          <td><%= ModuleRedcarpetAux.md2safehtml(engage.note) %></td>
          <td><%= engage.harami1129s.count %></td>
          <td></td>
          <td><%= link_to 'Show', engage %></td>
          <% if current_user.sysadmin? %>
            <td><%= link_to 'Destroy(Admin)', engage, method: :delete, data: { confirm: t('are_you_sure') } %></td>
          <% end %>
        </tr>
      <% end %>
      <% if !@engage_others.exists? %>
      <tr>
        <td></td>
        <td colspan="<%= n_cols-1 %>">None</td>
      </tr>
      <% end %>
    </tbody>
  </table>
  <% assoc_text = t(".assoc_engage", music_title: music_name, default: "with another Artist for #{music_name}") %>
  <%= button_to t('layouts.create_model', model: "Engage", default: 'Create a new Engage'), new_engage_path, method: :get, params: { music_id: @music.id }, form_class: "button_to inline_form" %> <%# button_to HTML-class is Default.%>
  <%= t(".assoc_engage", music_title: music_name, default: "with another Artist for #{music_name}") %> <%# button_to/link_to title tested in /system/engages_test.rb; if it is link_to, the path should be new_engage_path(music_id: @music.id) %>
<% if (n_engages == 1) && (n_engage_others == 0) && @engages[0] && @engages[0].harami1129s.exists? %>
  <p>
    <em>Note</em>: If you want to destroy the (sole) Engage, you must first create another Engage, because the existing one has a dependent Harami1129(s).
      If you are sure the Harami1129(s) should have no Engage whatsoever, meaning with neither Artist nor Music, go to <%= link_to 'Harami1129', edit_harami1129_url(@engages[0].harami1129s[0]) %> and destroy it first.
  </p>
<% end %>