config/routes.rb
Rails.application.routes.draw do
  ####### This part MUST precede any other lines!!
  #filter :extension #, :exclude => %r(^admin/)
  filter :locale#,    :exclude => /^\/admin/
  default_url_options(locale: I18n.locale) if Rails.env.test?  # manually defined in application_controller.rb
  ####### Up to here

  resources :diagnose, only: [:index]
  resources :urls
  resources :domains
  resources :domain_titles
  resources :site_categories
  resources :channels
  namespace :channels do
    resources :fetch_youtube_channels, only: [:update]  # may add :create in future
  end
  resources :channel_owners
  namespace :channel_owners do
    get 'create_with_artists/new'
  end
  resources :channel_types
  resources :channel_platforms
  resources :harami_vid_music_assocs, only: [:destroy]
  namespace :harami_vid_music_assocs do
    resources :timings, only: [:show, :edit, :update]
    resources :notes,   only: [:show, :edit, :update]
  end
  resources :artist_music_plays, only: [:destroy]
  namespace :artist_music_plays do
    resources :edit_multis, only: [:index, :edit, :update, :create, :show]
  end
  resources :instruments
  resources :play_roles
  namespace :events do
    resources :align_start_time_with_vid, only: [:show, :update]
  end
  resources :event_items
  namespace :event_items do
    resources :nominal_machine_titles, only: [:show, :update]
    resources :match_parents,     only: [:update]
    resources :deep_duplicates,   only: [:create]
    resources :destroy_with_amps, only: [:destroy]
    resources :resettle_new_events, only: [:update]
  end
  resources :harami1129_reviews
  resources :event_groups
  resources :model_summaries
  namespace :translations do  # "update" is used so that it can be handled with Ability
    get ':id/promotes/update', to: 'promotes#update', as: :update_promotes # => translations_update_promote_path(:id) => /translations/:id/promotes/update
    get ':id/demotes/update',  to: 'demotes#update',  as: :update_demotes  # => translations_update_demote_path(:id)  => /translations/:id/demotes/update
  end
  namespace :artists do
    resources :ac_titles, only: [:index]
    get    ':id/merges/new',  to: 'merges#new',     as: :new_merges  # => artists_new_merge_path(:id)  => /artists/:id/merges/new
    get    ':id/merges/edit', to: 'merges#edit',    as: :edit_merges # => artists_edit_merge_path(:id) => /artists/:id/merges/edit
    match  ':id/merges',      to: 'merges#update',  as: :update_merges, via: [:put, :patch]
    namespace :merges do
      get 'artist_with_ids',   to: 'artist_with_ids#index'  # => artists_merges_artist_with_ids_path => /artists/merges/artist_with_ids#index
    end
  end
  resources :page_formats

  resources :static_pages
  resources :country_masters
  namespace :country_masters do
    post   ':id/create_countries',  to: 'create_countries#update', as: :create_countries  # => country_masters_create_countries_path(:id)  => /country_masters/:id/create_countries
  end

  namespace :musics do
    resources :ac_titles, only: [:index]  # changed from: get 'ac_titles/index'
    get    ':id/merges/new',  to: 'merges#new',     as: :new_merges  # => musics_new_merge_path(:id)  => /musics/:id/merges/new
    get    ':id/merges/edit', to: 'merges#edit',    as: :edit_merges # => musics_edit_merge_path(:id) => /musics/:id/merges/edit
    match  ':id/merges',      to: 'merges#update',  as: :update_merges, via: [:put, :patch]
    resources :upload_music_csvs, only: [:create]
    namespace :merges do
      get 'music_with_ids',   to: 'music_with_ids#index'  # => musics_merges_music_with_ids_path => /musics/merges/music_with_ids#index
    end
  end
  resources :engage_multi_hows, only: [:index, :show, :edit, :create]
  resources :engages, only: [:index, :show, :new, :create, :destroy]
  resources :engage_hows
  #get 'user_role_assoc/update'
  resources :user_role_assoc, only: :update
  namespace :users do
    resources :edit_roles, only: [:update]
    ##resource :confirm, only: :update
    #resources :confirm, only: :update
    match  ':id/confirms', to: 'confirms#update', as: :confirm, via: [:put, :patch]
    get    ':id/deactivate_users/edit', to: 'deactivate_users#edit',    as: :edit_deactivate_users # => users_edit_deactivate_users_path(:id) => /users/:id/deactivate_users/edit
    match  ':id/deactivate_users',      to: 'deactivate_users#update',  as: :do_deactivate_users, via: [:put, :patch]
    delete ':id/deactivate_users',      to: 'deactivate_users#destroy', as: :destroy_deactivate_users  # NOTE: without "as", the prefix would be "users"
  end

  get 'users/index'
  resources :harami1129s
  resources :harami1129s do
    resource :populate,            only: [:update], module: 'harami1129s'
    resource :internal_insertions, only: [:update], module: 'harami1129s'
  end
  namespace :harami1129s do
    resource :download_harami1129s, only: [:new]
    resource :inject_from_harami1129s, only: [:create]
    post     :internal_insertions, to: 'internal_insertions#update_all'
    #patch     :internal_insertions, to: 'internal_insertions#update_all'
    #put       :internal_insertions, to: 'internal_insertions#update_all'  # Patch and Put does not work: Rails.application.routes.recognize_path("/harami1129s/internal_insertions", method: :put) #=> {:controller=>"harami1129s", :action=>"update", :id=>"internal_insertions"}
  end
  resources :harami_vids do
    resource :upload_hvma_csv, only: [:create], controller: 'harami_vids/upload_hvma_csvs'
    # => POST   /harami_vids/:harami_vid_id/upload_hvma_csvs
    #   params are like: params[:harami_vid_id] and params[:upload_hvma_csv][:filename]
    # NOte: "resources :upload_hvma_csvs" (note the plural) would do virtually the same, but "resource" is semantically cleaner.
  end
  namespace :harami_vids do
    resources :fetch_youtube_data, only: [:create, :update]
    resources :update_places,      only: [:show,   :update]
    resources :add_missing_music_to_evits, only: [:show,   :update]
  end
  resources :genres
  resources :translations
  resources :places
  resources :prefectures
  resources :countries
  resources :roles
  resources :role_categories
  resources :sexes

  ## WARNING: It seems the following MUST come after namespace definitions (of :artists and :musics, specifically).  Otherwise, auto-completion would not work...
  %w(artists events harami_vids musics places).each do |model_plural|
    resources model_plural.to_sym do
      resources :anchorings, controller: model_plural+'/anchorings'
    end
  end

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  # devise_for :users  # Default
  devise_for :users, :except => [:destroy]
  # devise_for :users, :path_prefix => 'd'  # => /usrs/d/sign_up etc
  resources :users, :only =>[:show]
  #match '/users/:id',     to: 'users#show',       via: 'get'
  #match '/users/:id',     to: 'users#show',  :as => :user,     via: 'get'
  root to: "home#index"
  get 'home/index'

  match '/users',   to: 'users#index',   via: 'get'
  ##resources :users do
  ##  resource :user_lists, only: [:index], module: 'users'
  ##end
  #namespace :users do
  #  get      :user_lists, only: [:index], to: 'user_lists#index'
  #  post     :user_lists, only: [:index], to: 'user_lists#index'
  #end

  # Arbitrary page paths are dealt with StaticPagePublicsController
  get '/static_page_publics', to: 'static_page_publics#index'
  constraints(lambda { |request| !File.basename(request.fullpath).sub(/\?.*/, '').include?('.') }) do
    # Except the filenames with a suffix like .jpg or even .html
    get '*path', to: 'static_page_publics#show'
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/translations/demotes_controller.rb
class Translations::DemotesController < ApplicationController

  before_action :set_translation, only: [:update]

  # True if demote is allowed.
  #
  # Essentially, this Controller (but this class method) is only accessible 
  # by translation-moderators and admins.  They are allowed to demote
  # almost any Translations, created by whomever, unless the {#weight} is
  # already zero.
  #
  # Note that if the Translation with the highest weight score among sibling Translations
  # is created by a senior person (admin), the demoted weight would not exceed it.
  # Mind you, most of admin-created translations should have a weight of either
  # 0 (i.e., {#is_orig}==true or definitive translation) or Infinity
  # and nothing in between, although admin's default Translation weight is 1.
  #
  # @param tra [Translation]
  # @param user [User]
  def self.allowed?(tra, user=ModuleWhodunnit.whodunnit)
    # return false if !can?(:update, Translations::DemotesController)  # This check should be done in UI (View). Besides, it is a bit awkward to use "can?" here.
    return false if tra.weight && tra.weight == Float::INFINITY
    return false if tra.is_orig  # Original one cannot be demoted. Moderator may modify is_orig
    return false if tra.siblings(exclude_self: false).last == tra

    role = user.highest_role_in(RoleCategory[RoleCategory::MNAME_TRANSLATION])
    return false if !tra.create_user
    return true  if  tra.create_user == user
    other_user = tra.create_user
    return false if !other_user  # If create_user is undefined weight should be either 0 or Float::INFINITY anyway
    other_role = other_user.highest_role_in(RoleCategory[RoleCategory::MNAME_TRANSLATION])
    return false if !role.superior_to?(other_role)  # If you're at the same rank, you cannot demote it.
    return true
  end

  def update
    authorize! :update, Translations::DemotesController

    if !self.class.allowed?(@translation, current_user)
      # The UI should be designed not to reach this point.
      raise CanCanCan::AccessDenied.new("Not authorized to demote Translation=#{@translation.title_or_alt.inspect}", :update, Translations::DemotesController)
    end

    new_weight, hsbest = @translation.weight_after_next
    opts = {}

    if new_weight && @translation.update(weight: new_weight)
      is_qualified = current_user.qualified_as?('moderator', RoleCategory[RoleCategory::MNAME_TRANSLATION])
      msgweight = (is_qualified ? " with a new weight of #{new_weight}." : "")
      msg1 = "Successfully demoted the Translation (title_or_alt=#{@translation.title_or_alt.inspect})"+msgweight
      msgweight = (is_qualified ? sprintf(" (ID=%d, weight=%s).", hsbest[:id], hsbest[:weight]) : ".")
      msg2 = "The highest-priority [#{@translation.langcode}] Translation is now #{hsbest[:title].inspect}"+msgweight
      opts[:success] = [msg1, msg2].join(" ")

      respond_to do |format|
        format.html { redirect_to (request.referrer || @translation), **opts }
        format.json { render json: [opts[:success]], status: :ok, location: (request.referrer || @translation) }
      end
    else
      if new_weight
        # This should not happen in general (unless DB behaves funny.)
        opts[:alert] = @translation.errors.full_messages if !@translation.errors.empty?
      else
        # The weight of the next one is Float::INFINITY (or possibly nil, though nil is banned; see callback set_create_user)
        opts[:alert] = "The next one has the worst weight (quality) and hence you cannot demote this Translation."
      end
      msg = (opts[:alert] || opts[:warning])
      respond_to do |format|
        format.html { redirect_to (request.referrer || @translation), **opts }
        format.json { render json: [msg], status: :unprocessable_content }
      end
    end
  end

  private
    # Use callback for setup for new
    def set_translation
      @translation = Translation.find(params[:id])
    end

end

app/helpers/translations_helper.rb
module TranslationsHelper
  # @example
  #    <td><%= cell_ruby_romaji(modelx) %></td> <%# defined in translations_helper.rb %>
  #
  # @param model [ApplicationRecord]
  # @return [String]
  def cell_ruby_romaji(model, langcode: 'ja')
    ar = %i(ruby romaji).map{|i| model.send(i, langcode: langcode, lang_fallback: false, str_fallback: "")}
    ar.join("").blank? ? "" : sprintf('[%s/%s]', *ar)
  end

  # @example
  #    <td><%= cell_alt_all(modelx) %></td> <%# defined in translations_helper.rb %>
  #
  # @param model [ApplicationRecord]
  # @return [String]
  def cell_alt_all(model, langcode: 'ja')
    ar = %i(alt_title alt_ruby alt_romaji).map{|i| model.send(i, langcode: langcode, lang_fallback: false, str_fallback: "")}
    ar[1..2].join("").blank? ? ar[0] : sprintf('%s [%s/%s]', *ar)
  end

  # @example
  #    <td><%= cell_tit_alt(modelx) %></td> <%# defined in translations_helper.rb %>
  #
  # @param model [ApplicationRecord]
  # @return [String]
  def cell_tit_alt(model, langcode: 'en')
    ar = %i(title alt_title).map{|i| model.send(i, langcode: langcode, lang_fallback: false, str_fallback: "")}
    ar[1].blank? ? ar[0] : sprintf('%s [%s]', *ar)
  end

  # @example
  #    print_two_with_brackets(tra.ruby, tra.romaji)
  #     # => "[ | tokyo]"  or  ""
  #     # => maybe "[ | ]" (editor) or  "" (public)
  #
  # @param s1 [String]
  # @param s2 [String, NilClass]
  # @return [String]
  def print_two_with_brackets(s1, s2=nil, separator: " | ")
    ar=[s1, s2]
    retstr = "["+ar.map{|i| i || ""}.join(separator)+"]"
    if (can?(:edit, Translation) || can?(:edit, Music)) || ar.any?(&:present?)
      retstr
    else
      ""
    end
  end

  # @param model [BaseWithTranslation]
  # @return [String] checked for select in Form
  def langcode_checked(model)
    if defined?(@hstra) && @hstra["langcode"].present?
      # set in set_hsparams_main_tra in application_controller.rb providing the Controller uses it.
      # @hstra is set only after create (or update) and NOT in new (or edit, but note
      # this routine should be irrelevant for "edit", because the form of BaseWithTranslation
      # for :edit does not include Translation fields).
      @hstra["langcode"]
    elsif model.respond_to?(:langcode) && model.langcode.present?
      model.langcode
    elsif (tras=model.best_translation).present?
      tras.langcode
    else
      I18n.available_locales.first.to_s  # "ja"
    end
  end

  # @param model [BaseWithTranslation, NilClass]
  # @param key [Symobol, String] :title, :alt_title, :ruby, etc.
  # @return [String] checked for select in Form
  def value_a_title_in_form(model, key)
    key = key.to_s
    if defined?(@hstra) && @hstra[key].present?
      # set in set_hsparams_main_tra in application_controller.rb providing the Controller uses it.
      # @hstra is set only after create or update and NOT in new or edit.
      @hstra[key]
    elsif model.respond_to?(key) && (val=model.send(key)).present?
      val
    else
      ""
    end
  end
end

app/views/translations/_form.html.erb
<%= render partial: 'layouts/form_print_errors', locals: {model: translation} %>

<%= form_with(model: translation, local: true) do |form| %>
  <% if ! translation.new_record? %>
    <p>
      ID=<%= translation.id %>
    </p>
  <% end %>

  <div class="field">
    <%= form.label :translatable_type %>
    <%= form.text_field :translatable_type, readonly: !!translation.translatable_type, class: "input_middle" %>
  </div>

  <div class="field">
    <%= form.label :translatable_id %>
    <%= form.text_field :translatable_id, readonly: !!translation.translatable_id, class: "input_int" %>
  </div>

  <div class="field">
    <%= form.label :langcode %>
    <%= form.text_field :langcode, class: "input_shortest" %>
      <span class="small">"es" (Spanish), "it" (Italian), "de" (German), "ko" (Korean), "zh" (Chinese), etc</span>
  </div>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_area :title %>
  </div>

  <div class="field">
    <%= form.label :ruby %>
    <%= form.text_area :ruby %>
  </div>

  <div class="field">
    <%= form.label :romaji %>
    <%= form.text_area :romaji %>
  </div>

  <div class="field">
    <%= form.label :alt_title %>
    <%= form.text_area :alt_title %>
  </div>

  <div class="field">
    <%= form.label :alt_ruby %>
    <%= form.text_area :alt_ruby %>
  </div>

  <div class="field">
    <%= form.label :alt_romaji %>
    <%= form.text_area :alt_romaji %>
  </div>

  <div class="field">
    <% if translation.is_orig
         checked = :original
       else
         translat = translation.translatable
         checked =
           if translat && translat.translations.where(is_orig: true).exists?
             :translation
           else
             :undefined
           end
       end
      %>
    <%= form.label :is_orig, 'Translation category' %>
    <%= form.radio_button(:is_orig, true, checked: (:original == checked)) %>
    <%= form.label :is_orig, '原語', :value => true %>
    <%= form.radio_button(:is_orig, false, checked: (:translation == checked)) %>
    <%= form.label :is_orig, '翻訳', :value => false %>
    <%= form.radio_button(:is_orig, "nil", checked: (:undefined == checked)) %>
    <%= form.label :is_orig, '定義不能 (例:「太陽⇔Sun」)', :value => "nil" %>
  </div>

  <% if (user_signed_in? && current_user.qualified_as?(:moderator, RoleCategory[RoleCategory::MNAME_TRANSLATION])) %>
  <div class="field">
    <% str_table = (translation.translatable.respond_to?(:translations) ? 'See table below for reference. ' : '') %>
    <%= form.label :weight, "Weight (#{str_table}Set it under 100 to promote this permanently, 0 for the definitive word like the original one.)" %>
    <%= form.text_field :weight, class: "input_float" %>
  </div>
  <% end %>

  <% if user_signed_in? && current_user.an_admin? %>
  <div class="field">
    <%= form.label :create_user_id %>
    <%= form.text_field :create_user_id %>
  </div>

  <div class="field">
    <%= form.label :update_user_id %>
    <%= form.text_field :update_user_id %>
  </div>
  <% end %>

  <div class="field">
    <%= form.label :note %>
    <%= form.text_area :note %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

<% if ! translation.new_record? && can?(:destroy, translation) %>
  <div class="actions-destroy" style="margin-right: 1em;">
   <div class="actions" style="text-align: right">
     <% if translation.translatable.translations.count > 1 && !translation.is_orig %>
       <%= button_to 'Destroy', translation, method: :delete, data: { confirm: t('are_you_sure') } %>
     <% else %>
       <form class="button_to"><input disabled="disabled" type="submit" value="Destroy"></form>
      <% if translation.is_orig %>
       (This is the original Translation for the instance and so cannot be destroyed.)
      <% else %>
       (This is the only Translation for the instance and so cannot be destroyed.)
      <% end %>
     <% end %>
   </div>
  </div>
<% end %>

<p>
  <% if ! translation.new_record? %>
    <%= link_to 'Show', translation %> |
  <% end %>
  <%= link_to 'Back to Index', translations_path %>
</p>

<% if translation.translatable.respond_to? :translations %>
  <%= render partial: 'layouts/all_registered_translations', locals: {model: translation.translatable, add_buttons: false, myself: translation} %>
  <hr>
<% end %>

app/views/translations/edit.html.erb
<h1>Editing Translation</h1>

<%= render 'form', translation: @translation %>

<%= link_to 'Show', @translation %> |
<%= link_to 'Back', translations_path %>

app/views/translations/index.html.erb
<h1>Translations <%= h1_note_editor_only(Translation, method: :index) %></h1>

<% if false %>
<table>
  <thead>
    <tr>
      <th>Id</th>
      <th colspan="2">Translatable</th>
      <th>Lang</th>
      <th>Title</th>
      <th>Alt title</th>
      <th>Ruby</th>
      <th>Alt ruby</th>
      <th>Romaji</th>
      <th>Alt romaji</th>
      <th>Orig?</th>
      <th>Weight</th>
      <th>Create user</th>
      <th>Update user</th>
      <th>Note</th>
      <%# See below to see why this is cancelled <th colspan="3"></th> %>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @translations.each do |translation| %>
      <% next if cannot? :read, translation %>
      <tr>
        <td><%= translation.id %></td>
        <% model = translation.translatable_type.classify.constantize %>
        <td><%= link_to translation.translatable_type, polymorphic_path(model) %></td>
        <td><%= link_to translation.translatable_id, polymorphic_path(model.find(translation.translatable_id)) %></td>
        <td><%= translation.langcode %></td>
        <td><%= translation.title %></td>
        <td><%= translation.alt_title %></td>
        <td><%= translation.ruby %></td>
        <td><%= translation.alt_ruby %></td>
        <td><%= translation.romaji %></td>
        <td><%= translation.alt_romaji %></td>
        <td><%= translation.is_orig %></td>
        <td><%= translation.weight %></td>
        <td><%= translation.create_user_id ? @hsuser[translation.create_user_id].html_safe : ''%></td>
        <td><%= translation.update_user_id ? @hsuser[translation.update_user_id].html_safe : ''%></td>
        <td><%= translation.note %></td>
        <td class="cell_show"><%= link_to 'Show', translation %></td>
        <% if false %>
          <%# This is far too DB-heavy... It may take 1 minute to process 5000 records! Unless serious pagenation is introduced, this is not viable in practice. %>
          <% if can? :edit, translation %>
            <td class="cell_edit"><%= link_to 'Edit', edit_translation_path(translation) %></td>
            <% if can? :destroy, translation %>
              <td class="cell_destroy"><%= link_to 'Destroy', translation, method: :delete, data: { confirm: t('are_you_sure') } %></td>
            <% end %>
          <% end %>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>
<% end %>

<%= datagrid_form_with model: @grid, method: :get, url: translations_path %>

<%= paginate(@grid.assets) %>
<%= datagrid_table @grid %>
<%= paginate(@grid.assets) %>

<%= render "layouts/grid_table_tail", klass: Translation %>

<br>

<% if can? :create, Translation %>
 <div class="button_new">
  <%= button_to 'Create New Translation', new_translation_path, method: :get %>
  <%# link_to 'New Translation', new_translation_path %>
 </div>
<% end %>

app/views/translations/new.html.erb
<h1>New Translation</h1>

<%= render 'form', translation: @translation %>

<%= link_to 'Back to Index', (request.referrer || translations_path) %>

app/views/translations/show.html.erb
<h2>A Translation for <%= link_to @translation.translatable_type, @translation.translatable %>
  <% if cancrud=can?(:crud, Translation) %>
    ID=<%= @translation.translatable.id %>
    (Translation ID=<%= @translation.id %>)
  <% end %>
</h2>

<dl>
  <dt>Translatable:</dt>
  <dd><%= link_to @translation.translatable_type, @translation.translatable %></dd>

  <dt> Langcode:</dt>
  <dd><%= @translation.langcode %></dd>

  <dt> Title:</dt>
  <dd><%= @translation.title %></dd>

  <dt> Alt title:</dt>
  <dd><%= @translation.alt_title %></dd>

  <dt> Ruby:</dt>
  <dd><%= @translation.ruby %></dd>

  <dt> Alt ruby:</dt>
  <dd><%= @translation.alt_ruby %></dd>

  <dt> Romaji:</dt>
  <dd><%= @translation.romaji %></dd>

  <dt> Alt romaji:</dt>
  <dd><%= @translation.alt_romaji %></dd>

  <dt><%= t(".is_orig") %>:</dt>
  <dd><%= @translation.is_orig %></dd>

  <% if can? :crud, Translation %>
    <dt> Weight:</dt>
    <dd><%= @translation.weight %></dd>
  <% end %>

  <%= render partial: 'layouts/show_note_memo_timestamps', locals: {model: @translation, model4ability: cancrud} %>
</dl>

<% if user_signed_in? && @translation.editable?(user: current_user) %>
  <%= button_to 'Edit', edit_translation_path(@translation), method: :get %>
<br>
<% end %>
<%= link_to 'Back to Index', translations_path %>

<hr>

<%= render partial: 'layouts/all_registered_translations', locals: {model: @translation.translatable, myself: @translation, add_buttons: true} %>