config/routes.rb
Rails.application.routes.draw do
  ####### This part MUST precede any other lines!!
  #filter :extension #, :exclude => %r(^admin/)
  filter :locale#,    :exclude => /^\/admin/
  default_url_options(locale: I18n.locale) if Rails.env.test?  # manually defined in application_controller.rb
  ####### Up to here

  resources :diagnose, only: [:index]
  resources :urls
  resources :domains
  resources :domain_titles
  resources :site_categories
  resources :channels
  namespace :channels do
    resources :fetch_youtube_channels, only: [:update]  # may add :create in future
  end
  resources :channel_owners
  namespace :channel_owners do
    get 'create_with_artists/new'
  end
  resources :channel_types
  resources :channel_platforms
  resources :harami_vid_music_assocs, only: [:destroy]
  namespace :harami_vid_music_assocs do
    resources :timings, only: [:show, :edit, :update]
    resources :notes,   only: [:show, :edit, :update]
  end
  resources :artist_music_plays, only: [:destroy]
  namespace :artist_music_plays do
    resources :edit_multis, only: [:index, :edit, :update, :create, :show]
  end
  resources :instruments
  resources :play_roles
  namespace :events do
    resources :align_start_time_with_vid, only: [:show, :update]
  end
  resources :event_items
  namespace :event_items do
    resources :nominal_machine_titles, only: [:show, :update]
    resources :match_parents,     only: [:update]
    resources :deep_duplicates,   only: [:create]
    resources :destroy_with_amps, only: [:destroy]
    resources :resettle_new_events, only: [:update]
  end
  resources :harami1129_reviews
  resources :event_groups
  resources :model_summaries
  namespace :translations do  # "update" is used so that it can be handled with Ability
    get ':id/promotes/update', to: 'promotes#update', as: :update_promotes # => translations_update_promote_path(:id) => /translations/:id/promotes/update
    get ':id/demotes/update',  to: 'demotes#update',  as: :update_demotes  # => translations_update_demote_path(:id)  => /translations/:id/demotes/update
  end
  namespace :artists do
    resources :ac_titles, only: [:index]
    get    ':id/merges/new',  to: 'merges#new',     as: :new_merges  # => artists_new_merge_path(:id)  => /artists/:id/merges/new
    get    ':id/merges/edit', to: 'merges#edit',    as: :edit_merges # => artists_edit_merge_path(:id) => /artists/:id/merges/edit
    match  ':id/merges',      to: 'merges#update',  as: :update_merges, via: [:put, :patch]
    namespace :merges do
      get 'artist_with_ids',   to: 'artist_with_ids#index'  # => artists_merges_artist_with_ids_path => /artists/merges/artist_with_ids#index
    end
  end
  resources :page_formats

  resources :static_pages
  resources :country_masters
  namespace :country_masters do
    post   ':id/create_countries',  to: 'create_countries#update', as: :create_countries  # => country_masters_create_countries_path(:id)  => /country_masters/:id/create_countries
  end

  namespace :musics do
    resources :ac_titles, only: [:index]  # changed from: get 'ac_titles/index'
    get    ':id/merges/new',  to: 'merges#new',     as: :new_merges  # => musics_new_merge_path(:id)  => /musics/:id/merges/new
    get    ':id/merges/edit', to: 'merges#edit',    as: :edit_merges # => musics_edit_merge_path(:id) => /musics/:id/merges/edit
    match  ':id/merges',      to: 'merges#update',  as: :update_merges, via: [:put, :patch]
    resources :upload_music_csvs, only: [:create]
    namespace :merges do
      get 'music_with_ids',   to: 'music_with_ids#index'  # => musics_merges_music_with_ids_path => /musics/merges/music_with_ids#index
    end
  end
  resources :engage_multi_hows, only: [:index, :show, :edit, :create]
  resources :engages, only: [:index, :show, :new, :create, :destroy]
  resources :engage_hows
  #get 'user_role_assoc/update'
  resources :user_role_assoc, only: :update
  namespace :users do
    resources :edit_roles, only: [:update]
    ##resource :confirm, only: :update
    #resources :confirm, only: :update
    match  ':id/confirms', to: 'confirms#update', as: :confirm, via: [:put, :patch]
    get    ':id/deactivate_users/edit', to: 'deactivate_users#edit',    as: :edit_deactivate_users # => users_edit_deactivate_users_path(:id) => /users/:id/deactivate_users/edit
    match  ':id/deactivate_users',      to: 'deactivate_users#update',  as: :do_deactivate_users, via: [:put, :patch]
    delete ':id/deactivate_users',      to: 'deactivate_users#destroy', as: :destroy_deactivate_users  # NOTE: without "as", the prefix would be "users"
  end

  get 'users/index'
  resources :harami1129s
  resources :harami1129s do
    resource :populate,            only: [:update], module: 'harami1129s'
    resource :internal_insertions, only: [:update], module: 'harami1129s'
  end
  namespace :harami1129s do
    resource :download_harami1129s, only: [:new]
    resource :inject_from_harami1129s, only: [:create]
    post     :internal_insertions, to: 'internal_insertions#update_all'
    #patch     :internal_insertions, to: 'internal_insertions#update_all'
    #put       :internal_insertions, to: 'internal_insertions#update_all'  # Patch and Put does not work: Rails.application.routes.recognize_path("/harami1129s/internal_insertions", method: :put) #=> {:controller=>"harami1129s", :action=>"update", :id=>"internal_insertions"}
  end
  resources :harami_vids do
    resource :upload_hvma_csv, only: [:create], controller: 'harami_vids/upload_hvma_csvs'
    # => POST   /harami_vids/:harami_vid_id/upload_hvma_csvs
    #   params are like: params[:harami_vid_id] and params[:upload_hvma_csv][:filename]
    # NOte: "resources :upload_hvma_csvs" (note the plural) would do virtually the same, but "resource" is semantically cleaner.
  end
  namespace :harami_vids do
    resources :fetch_youtube_data, only: [:create, :update]
    resources :update_places,      only: [:show,   :update]
    resources :add_missing_music_to_evits, only: [:show,   :update]
  end
  resources :genres
  resources :translations
  resources :places
  resources :prefectures
  resources :countries
  resources :roles
  resources :role_categories
  resources :sexes

  ## WARNING: It seems the following MUST come after namespace definitions (of :artists and :musics, specifically).  Otherwise, auto-completion would not work...
  %w(artists events harami_vids musics places).each do |model_plural|
    resources model_plural.to_sym do
      resources :anchorings, controller: model_plural+'/anchorings'
    end
  end

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  # devise_for :users  # Default
  devise_for :users, :except => [:destroy]
  # devise_for :users, :path_prefix => 'd'  # => /usrs/d/sign_up etc
  resources :users, :only =>[:show]
  #match '/users/:id',     to: 'users#show',       via: 'get'
  #match '/users/:id',     to: 'users#show',  :as => :user,     via: 'get'
  root to: "home#index"
  get 'home/index'

  match '/users',   to: 'users#index',   via: 'get'
  ##resources :users do
  ##  resource :user_lists, only: [:index], module: 'users'
  ##end
  #namespace :users do
  #  get      :user_lists, only: [:index], to: 'user_lists#index'
  #  post     :user_lists, only: [:index], to: 'user_lists#index'
  #end

  # Arbitrary page paths are dealt with StaticPagePublicsController
  get '/static_page_publics', to: 'static_page_publics#index'
  constraints(lambda { |request| !File.basename(request.fullpath).sub(/\?.*/, '').include?('.') }) do
    # Except the filenames with a suffix like .jpg or even .html
    get '*path', to: 'static_page_publics#show'
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_action :authenticate_user!, :only => [:index]

  def index
    @message = ''
    @home_hvs = HaramiVid.order(release_date: :desc)[0..19]  # The latest 20 Videos
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<h1>Music-i18n.org for HARAMIchan (ハラミちゃん)</h1>
<div id="home-intro">
<p><%= t('.first_line_html') %><br>
   <%= t('.second_line') %></p>
<p><%= t('.third_line') %>
  <% if !user_signed_in? %>
    <%= t('.fourth_line1') %><%= link_to new_user_registration_path, class: 'register-button' do %><%= t("devise.registrations.new.sign_up") %><% end %><%= t('.fourth_line2') %>
  <% end %>
</p>
</div>

<p><%= @message %></p>

<p><%= link_to t('.harami_vids_index'), harami_vids_path %> | <%= link_to t('.musics_index'), musics_path %> | <%= link_to t('.artists_index'), artists_path %>
  <%= editor_only_safe_html(Translation, method: :index, tag: "span") do %>
    | <%= link_to 'Translations/翻訳', translations_path %>
  <% end %>
</p>

<h3><%= t('.h3_table') %></h3>

<table id="home_table_main">
  <thead>
    <tr>
      <th><%= t('tables.release_date', default: "Date") %></th>
      <th><%= t('.vid_title', default: "Video Title") %></th>
      <th title="English name of the original Artists of the played music; if the English name is not available, the Japanese name may be displayed"><%= t('application.menu_artists', default: "Artists") %> [<%= t('locale.capital.en', default: "EN") %>]</th>
      <th class="music_title_en"><%= t('.musics_title', default: "Songs") %> [<%= t('locale.capital.en', default: "EN") %>] (Youtube)</th>
      <th class="music_title_ja"><%= t('.musics_title', default: "Songs") %> [<%= t('locale.capital.ja', default: "JA") %>] (Youtube)</th>
      <th><%= t('.length_sec', default: "Length [s]") %></th>
      <th><%= t('Place', default: "Place") %></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @home_hvs.each do |home_hv| %>
      <tr>
        <td><%= home_hv.release_date %></td>
        <td><%= link_to_youtube home_hv.title(langcode: I18n.locale, lang_fallback: true), home_hv.uri %></td>
        <td><%= home_hv.view_home_artist 'en' %></td>
        <td class="music_title_en"><%= home_hv.view_home_music 'en' %></td>
        <td class="music_title_ja"><%= home_hv.view_home_music 'ja' %></td>
        <td><%= home_hv.duration || "" %></td>
        <td><%= pla = home_hv.place
                if !pla
                  ''  # This should not happen...
                else
                  ar = pla.title_or_alt_ascendants(langcode: I18n.locale, prefer_alt: true);
                  sprintf '%s %s(%s)', ar[1], ((ar[0] == Place::UnknownPlace[I18n.locale] || ar[0].blank?) ? '' : '— '+ar[0]+' '), ar[2]
                end
            %></td>
        <td><%= link_to t('detail', default: "Detail"), home_hv, title: "Internal link to the content" %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<hr>

<div id="home_bottom">
<p><%= link_to t('.harami_vids_index'), harami_vids_path %> | <%= link_to t('.musics_index'), musics_path %> | <%= link_to t('.artists_index'), artists_path %>
  <%= editor_only_safe_html(Translation, method: :index, tag: "span") do %>
    | <%= link_to 'Translations/翻訳', translations_path %>
  <% end %>
</p>
<p>
  <a href="https://harami-piano.com/"><%= t('Harami') %> Website</a> | <a href="https://www.youtube.com/channel/UCr4fZBNv69P-09f98l7CshA" title="Harami-chan's YouTube channel"><%= t('.youtube_channel') %></a> | @harami_piano <a href="https://twitter.com/harami_piano">Twitter</a> | <a href="https://www.instagram.com/harami_piano">Instagram</a> | <a href="https://www.tiktok.com/@haramipiano">TikTok</a> | <%= art = Artist.default; art.link_to_wikipedia('Wikipedia') if art %>
</p>

<% if user_signed_in? %>
    <%= link_to destroy_user_session_path, method: :delete do %><%= t('log_out') %><% end %>
<% else %>
    <%= link_to new_user_session_path, class: 'login-button' do %><%= t("devise.sessions.new.sign_in") %><% end %> (<%= t('or') %> <%= link_to new_user_registration_path, class: 'register-button' do %><%= t("devise.registrations.new.sign_up") %><% end %>)
<% end %>
</div>