config/routes.rb
Rails.application.routes.draw do
  ####### This part MUST precede any other lines!!
  #filter :extension #, :exclude => %r(^admin/)
  filter :locale#,    :exclude => /^\/admin/
  default_url_options(locale: I18n.locale) if Rails.env.test?  # manually defined in application_controller.rb
  ####### Up to here

  resources :diagnose, only: [:index]
  resources :urls
  resources :domains
  resources :domain_titles
  resources :site_categories
  resources :channels
  namespace :channels do
    resources :fetch_youtube_channels, only: [:update]  # may add :create in future
  end
  resources :channel_owners
  namespace :channel_owners do
    get 'create_with_artists/new'
  end
  resources :channel_types
  resources :channel_platforms
  resources :harami_vid_music_assocs, only: [:destroy]
  namespace :harami_vid_music_assocs do
    resources :timings, only: [:show, :edit, :update]
    resources :notes,   only: [:show, :edit, :update]
  end
  resources :artist_music_plays, only: [:destroy]
  namespace :artist_music_plays do
    resources :edit_multis, only: [:index, :edit, :update, :create, :show]
  end
  resources :instruments
  resources :play_roles
  namespace :events do
    resources :align_start_time_with_vid, only: [:show, :update]
  end
  resources :event_items
  namespace :event_items do
    resources :nominal_machine_titles, only: [:show, :update]
    resources :match_parents,     only: [:update]
    resources :deep_duplicates,   only: [:create]
    resources :destroy_with_amps, only: [:destroy]
    resources :resettle_new_events, only: [:update]
  end
  resources :harami1129_reviews
  resources :event_groups
  resources :model_summaries
  namespace :translations do  # "update" is used so that it can be handled with Ability
    get ':id/promotes/update', to: 'promotes#update', as: :update_promotes # => translations_update_promote_path(:id) => /translations/:id/promotes/update
    get ':id/demotes/update',  to: 'demotes#update',  as: :update_demotes  # => translations_update_demote_path(:id)  => /translations/:id/demotes/update
  end
  namespace :artists do
    resources :ac_titles, only: [:index]
    get    ':id/merges/new',  to: 'merges#new',     as: :new_merges  # => artists_new_merge_path(:id)  => /artists/:id/merges/new
    get    ':id/merges/edit', to: 'merges#edit',    as: :edit_merges # => artists_edit_merge_path(:id) => /artists/:id/merges/edit
    match  ':id/merges',      to: 'merges#update',  as: :update_merges, via: [:put, :patch]
    namespace :merges do
      get 'artist_with_ids',   to: 'artist_with_ids#index'  # => artists_merges_artist_with_ids_path => /artists/merges/artist_with_ids#index
    end
  end
  resources :page_formats

  resources :static_pages
  resources :country_masters
  namespace :country_masters do
    post   ':id/create_countries',  to: 'create_countries#update', as: :create_countries  # => country_masters_create_countries_path(:id)  => /country_masters/:id/create_countries
  end

  namespace :musics do
    resources :ac_titles, only: [:index]  # changed from: get 'ac_titles/index'
    get    ':id/merges/new',  to: 'merges#new',     as: :new_merges  # => musics_new_merge_path(:id)  => /musics/:id/merges/new
    get    ':id/merges/edit', to: 'merges#edit',    as: :edit_merges # => musics_edit_merge_path(:id) => /musics/:id/merges/edit
    match  ':id/merges',      to: 'merges#update',  as: :update_merges, via: [:put, :patch]
    resources :upload_music_csvs, only: [:create]
    namespace :merges do
      get 'music_with_ids',   to: 'music_with_ids#index'  # => musics_merges_music_with_ids_path => /musics/merges/music_with_ids#index
    end
  end
  resources :engage_multi_hows, only: [:index, :show, :edit, :create]
  resources :engages, only: [:index, :show, :new, :create, :destroy]
  resources :engage_hows
  #get 'user_role_assoc/update'
  resources :user_role_assoc, only: :update
  namespace :users do
    resources :edit_roles, only: [:update]
    ##resource :confirm, only: :update
    #resources :confirm, only: :update
    match  ':id/confirms', to: 'confirms#update', as: :confirm, via: [:put, :patch]
    get    ':id/deactivate_users/edit', to: 'deactivate_users#edit',    as: :edit_deactivate_users # => users_edit_deactivate_users_path(:id) => /users/:id/deactivate_users/edit
    match  ':id/deactivate_users',      to: 'deactivate_users#update',  as: :do_deactivate_users, via: [:put, :patch]
    delete ':id/deactivate_users',      to: 'deactivate_users#destroy', as: :destroy_deactivate_users  # NOTE: without "as", the prefix would be "users"
  end

  get 'users/index'
  resources :harami1129s
  resources :harami1129s do
    resource :populate,            only: [:update], module: 'harami1129s'
    resource :internal_insertions, only: [:update], module: 'harami1129s'
  end
  namespace :harami1129s do
    resource :download_harami1129s, only: [:new]
    resource :inject_from_harami1129s, only: [:create]
    post     :internal_insertions, to: 'internal_insertions#update_all'
    #patch     :internal_insertions, to: 'internal_insertions#update_all'
    #put       :internal_insertions, to: 'internal_insertions#update_all'  # Patch and Put does not work: Rails.application.routes.recognize_path("/harami1129s/internal_insertions", method: :put) #=> {:controller=>"harami1129s", :action=>"update", :id=>"internal_insertions"}
  end
  resources :harami_vids do
    resource :upload_hvma_csv, only: [:create], controller: 'harami_vids/upload_hvma_csvs'
    # => POST   /harami_vids/:harami_vid_id/upload_hvma_csvs
    #   params are like: params[:harami_vid_id] and params[:upload_hvma_csv][:filename]
    # NOte: "resources :upload_hvma_csvs" (note the plural) would do virtually the same, but "resource" is semantically cleaner.
  end
  namespace :harami_vids do
    resources :fetch_youtube_data, only: [:create, :update]
    resources :update_places,      only: [:show,   :update]
    resources :add_missing_music_to_evits, only: [:show,   :update]
  end
  resources :genres
  resources :translations
  resources :places
  resources :prefectures
  resources :countries
  resources :roles
  resources :role_categories
  resources :sexes

  ## WARNING: It seems the following MUST come after namespace definitions (of :artists and :musics, specifically).  Otherwise, auto-completion would not work...
  %w(artists events harami_vids musics places).each do |model_plural|
    resources model_plural.to_sym do
      resources :anchorings, controller: model_plural+'/anchorings'
    end
  end

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  # devise_for :users  # Default
  devise_for :users, :except => [:destroy]
  # devise_for :users, :path_prefix => 'd'  # => /usrs/d/sign_up etc
  resources :users, :only =>[:show]
  #match '/users/:id',     to: 'users#show',       via: 'get'
  #match '/users/:id',     to: 'users#show',  :as => :user,     via: 'get'
  root to: "home#index"
  get 'home/index'

  match '/users',   to: 'users#index',   via: 'get'
  ##resources :users do
  ##  resource :user_lists, only: [:index], module: 'users'
  ##end
  #namespace :users do
  #  get      :user_lists, only: [:index], to: 'user_lists#index'
  #  post     :user_lists, only: [:index], to: 'user_lists#index'
  #end

  # Arbitrary page paths are dealt with StaticPagePublicsController
  get '/static_page_publics', to: 'static_page_publics#index'
  constraints(lambda { |request| !File.basename(request.fullpath).sub(/\?.*/, '').include?('.') }) do
    # Except the filenames with a suffix like .jpg or even .html
    get '*path', to: 'static_page_publics#show'
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/musics/ac_titles_controller.rb
# coding: utf-8

class Musics::AcTitlesController < BaseAutoCompleteTitlesController
  skip_before_action :authenticate_user!, :only => [:index]  # Revert application_controller.rb so Index is accessible by anyone.

  # This constant should be defined in each sub-class of BaseAutoCompleteTitlesController (and BaseMergesController)
  MODEL_SYM = :music

  #def index
  #  super
  #end
end

app/controllers/musics/anchorings_controller.rb
class Musics::AnchoringsController < BaseAnchorablesController
  # Essential constant used in the parent class BaseAnchorablesController
  ANCHORABLE_CLASS = self.name.split(":").first.singularize.constantize # Music class
end

app/controllers/musics/merges/music_with_ids_controller.rb
# coding: utf-8

class Musics::Merges::MusicWithIdsController < ApplicationController

  authorize_resource :class => false
  #skip_before_action :authenticate_user!, :only => [:index]  # action defined in application_controller.rb
  skip_authorize_resource
  #skip_authorization_check

  # Maximum number of candidates.
  MAX_SUGGESTIONS = 15

  def index
    idcur = get_id
    if !idcur
      return respond_to do |format|
        format.html { }
        format.json { render json: {error: "Forbidden request to #{params[:path].inspect}" }, status: :unprocessable_entity }
      end
    end

    candidates = Music.find(get_id).select_titles_partial_str_except_self(:titles, params[:keyword], display_id: true)

    respond_to do |format|
      format.html { }
      format.json { render json: candidates[0..MAX_SUGGESTIONS], status: :ok }
    end
  end  

  private
    # @rerutn [Integer, NilClass] rejects requests from a different page or site.
    def get_id
      # hs = Rails.application.routes.recognize_path params[:path], method: :get  # this works in Console, but does not work in test...
      # => {:controller=>"musics/merges", :action=>"new", :id=>"8", :locate=>"en"}
#logger.debug "DEBUG(#{__FILE__}): recognize_path(#{params[:path]})="+hs.inspect
      # baseroot = File.dirname(__FILE__).sub(%r@\A.+\bapp/controllers/@, "") # => "/en/musics/21923907/merges/new"
      # dirs = hs[:controller].split("/")  # "musics/merges"
      # if /\A#{Regexp.quote(dirs[0])}/ =~ baseroot && baseroot.include?(dirs[1])
      #   (%w(new edit).include? hs[:action])
      #   hs[:id].to_i
      mat = %r@\bmusics/(\d+)/merges\b@.match(params[:path])
      if mat
        mat[1].to_i
      else
        logger.warn "Rejects AJAX (or HTTP) request to #{__FILE__} from #{params[:path]}"
        nil
      end
    end

end

app/controllers/musics/merges_controller.rb
class Musics::MergesController < BaseMergesController
  # This constant should be defined in each sub-class of BaseMergesController
  # to indicate the mandatory parameter name for +params+
  MODEL_SYM = :music

  # Array of used keys in the form of the class like :other_music_id (or :other_artist_id)
  FORM_MERGE_KEYS = %i(other_artist_id other_artist_title to_index lang_orig lang_trans engage prefecture_place genre year note)

  before_action :set_music,  only: [:new]
  before_action :set_musics, only: [:edit, :update]

  # @raise [ActionController::UrlGenerationError] if no Music ID is found in the path.
  def new
  end

  # @raise [ActionController::UrlGenerationError] if no Music ID is found in the path.
  # @raise [ActionController::ParameterMissing] if the other Music ID is not specified (as GET).
  def edit
    msg = _msg_if_invalid_prm_in_merging(@musics, "Music") # defined in base_merges_controller.rb

    if msg  # e.g., when non-existent Music-ID is specified by the user.
      return respond_to do |format|
        format.html { redirect_to musics_new_merges_path(@musics[0]), alert: msg } # status: redirect
        format.json { render json: {error: msg}, status: :unprocessable_content }
      end
    end
    @merged_music = get_merged_model(@musics)  # defined in base_merges_controller.rb
    @all_checked_disabled = all_checked_disabled(@musics) # defined in base_merges_controller.rb
  end

  def update
    raise 'This should never happen - necessary parameter is missing. params='+params.inspect if 2 != @musics.size
    @all_checked_disabled = all_checked_disabled(@musics) # defined in base_merges_controller.rb

    mdl_self, mdl_other, priorities = get_self_other_priorities(@musics)
    begin
      ActiveRecord::Base.transaction(requires_new: true) do
        _ = mdl_self.merge_other(mdl_other, priorities: priorities, save_destroy: true, user: current_user)
        #raise ActiveRecord::Rollback, "Force rollback." if ...
      end
    rescue
      msg = "ERROR(#{File.basename __FILE__}): merging failed: ID(after-merged)=#{mdl_self.id}; models=#{@musics.inspect}"
      logger.error msg
      warn msg
      raise ## Transaction failed!  Rolled back.
    end

    _update_render(@musics)  # defined in base_merges_controller.rb
  end

  private
    # Use callback for setup for new
    def set_music
      @music = Music.find(params[:id])
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_musics
      set_to_index  # set @to_index; defined in base_merges_controller.rb

      @musics = []
      @musics << Music.find(params[:id])
      begin
        @musics << get_other_model(@musics[0])  # defined in base_merges_controller.rb
      rescue ActiveRecord::RecordNotFound
        # Specified Title for Edit is not found.  For update, this should never happen through UI.
        # As a result, @musics.size == 1
        raise if :edit != action_name.to_sym
      end
    end

end

app/helpers/musics_helper.rb
# coding: utf-8
module MusicsHelper

  # @param with_note: [Boolean] if true, all Engage#note for the music and artist is also included in the returned object
  # @return [Array[String,Engage]] maybe hyperlink (if permitted)
  def engage_title_link(music, artist, with_note: false)
    ## construct a Hash (key of year (9999 for nil)) of Arrays of Hashes
    hsyear = {}  #
    artist.engage_how_list(music).each do |ea_hs|  # [Engage,Title,Year,Contribution]
      if hsyear.keys.include?(yr=(ea_hs[:year] || 9999))  # 9999 is an impossibly large year used for sorting (see below)
        hsyear[yr] << ea_hs
      else
        hsyear[yr] = [ea_hs]
      end
    end

    return [] if hsyear.empty?

    can_read = can?(:read, (e1=hsyear.first[1].first[:engage]))  # If one can read one Engage, they should be allowed to read any Engage.
      # n.b., Hash#first gives a pair of Array(key, value)
    can_update = can?(:update, e1)

    years = hsyear.keys.sort
    retstr = years.map{ |eyr|
      conts = hsyear[eyr].map{ |ehs|
        ehs[:contribution] && print_1or2digits(ehs[:contribution])  # defined in application_helper.rb
      }
      contribution_str =
        if !can_update || conts.compact.empty?
          String.new
        else
          '<span class="editor_only">;f=' + conts.map{|i| i ? i : "nil"}.join("/") + "</span>"
        end

      if with_note
        notes = hsyear[eyr].map{ |ehs| ehs[:note].present? ? ehs[:note] : nil}
        compact_notes = notes.compact.map(&:strip)
        if !compact_notes.empty?
          contribution_str << editor_only_safe_html(:pass, method: can_update, tag: "span", text: ModuleRedcarpetAux.md2safehtml(";"+compact_notes.join("/")))
        end
      end

      hsyear[eyr].map{ |ehs|
        dagger_contribution =
          if ehs[:contribution] && ehs[:contribution] != 1
            sprintf '<span title="%s: %s">†</span>', t("attr.contribution"), print_percent_2digits(ehs[:contribution])
          else
            ""
          end.html_safe
        if can_read
          link_to ehs[:title], ehs[:engage]
        else
          ERB::Util.html_escape(ehs[:title]) 
        end + dagger_contribution
      }.join("/")+"("+((9999 == eyr) ? t('musics.show.year_unknown') : eyr.to_s)+contribution_str+")"
    }.join(t(:comma)).html_safe

    [retstr, hsyear.first[1].first[:engage]]
  end

  # You may encupsule this with ModuleRedcarpetAux.md2safehtml() or sanitized_html(with auto_link50(...)).html_safe
  #
  # @return [String] to show in a cell in Artist-Engage table in Music#show
  def compile_engage_notes(artist, music)
    arnotes = artist.engages.where(music: music).map{ |eng|
      if eng.note.present?
        sprintf("[%s] %s", eng.engage_how.title_or_alt(prefer_shorter: true, langcode: I18n.locale, lang_fallback_option: :either, str_fallback: "", article_to_head: true), eng.note.strip)
      else
        nil
      end
    }.compact.join(" \n")
  end

  # Returns String of html_safe (HTML-anchored) Music-titles up to a given maximum number.
  #
  # If it exceeds the given maximum number, a notice is appended.
  #
  # @example
  #    <%= list_linked_musics(ea_hvid.musics) %> <%# defined in MusicsHelper %>
  #
  # @param with_link: [Boolean] if true (Def), link_to is employed.
  # @return comma-separated html_safe Strings for many Music links
  def list_linked_musics(rela, max_items: 10, with_link: true, with_bf_for_trimmed: false)
    print_list_inline_upto(rela, model: Music, items_suffix: t(:music_noun).pluralize(I18n.locale), max_items: max_items, with_link: with_link, with_bf_for_trimmed: with_bf_for_trimmed)
  end
end

app/views/musics/_artists_table.html.erb
<h3><%= t("show.h2_artist").pluralize(music.artists.count, I18n.locale) %><%= t("show.h2_for") %><%= t("Music") %>: <%= music.title_or_alt_tuple_str(langcode: I18n.locale, lang_fallback_option: :either, article_to_head: true) %> (<%= music.year ? l(Date.new(music.year), format: :year) : t('musics.show.year_unknown') %>)</h3>

<%# local variables: music %>

<table>
  <thead>
    <tr>
     <% if (can_edit=can?(:edit, Artist)) %>
      <th title="DB pID" class="editor_only cell_pid">pID</th>
     <% end %>
      <th title="'*' indicates the original name"><%= t("tables.title_name_ja") %></th>
      <th><%= t("tables.alt_title_name_ja") %></th>
      <th title="'*' indicates the original name"><%= t("tables.title_name_en") %></th>
      <th title="Engagement between Artist and Music" class="cell_engage_how">
      <% if can? :update, EngageHow %>
        <%= link_to t('engage_multi_hows.table_head.how_related'), engage_hows_url %>
      <% else %>
        <%= t('engage_multi_hows.table_head.how_related') %>
      <% end %>
      </th>
      <th title="Place" class="cell_place"><%= t("tables.place_country") %></th>
      <th title="Birthday of the artist (person or group)" class="cell_birthday"><%= t('artists.show.birthday').capitalize %></th>
      <th class="cell_sex"> <%= can?(:update, Sex) ? link_to(t(:Sex), sexes_url) : t(:Sex) %> </th>
      <th class="cell_note"><%= t("tables.note") %></th>
      <% if can_edit %>
        <th colspan="2" title="Show/Edit Artist" class="cell_action"><%= t(:Artist) %></th>
      <% else %>
        <th title="Show Artist" class="cell_action"><%= t(:Artist) %></th>
      <% end %>
      <th class="cell_note_engage_how"><%= t("tables.note") %> (<%= t("engage_multi_hows.table_head.how_related") %>)</th>
      <% if can_edit %>
        <th title="Edit (Show) Engagements between Artist and Music" class="editor_only cell_action cell_edit_engage">Engages</th>
      <% end %>
    </tr>
  </thead>

  <tbody>
    <% asterisk = (can_edit ? ('<span title="'+t('datagrid.footnote.is_original')+'">*</span>') : "").html_safe %>
    <% music.sorted_artists.uniq.each do |artist| %>
      <tr>
       <% if can_edit %>
        <td title="DB pID" class="number editor_only cell_pid"><%= link_to artist.id, artist %></td>
       <% end %>
       <%= render partial: "layouts/tbody_title_ja_alt_en", locals: {model: artist, can_update: can_edit} %>
        <td class="cell_engage_how">
          <% linktxt, engage = engage_title_link(music, artist) %> <%# defined in musics_helper.rb %>
          <%= linktxt %>
        </td>
        <td class="cell_place"><%= artist.txt_place_pref_ctry(without_country_maybe: true) %></td>
        <td class="cell_birthday"><%= sprintf '%s年%s月%s日', *(%i(birth_year birth_month birth_day).map{|m|
                  i = artist.send m; (i.blank? ? '——' : i.to_s)}) %></td>
        <td class="text-center cell_sex"><%= artist.sex.title langcode: I18n.locale, lang_fallback: true %></td>
        <td class="cell_note"><%= ModuleRedcarpetAux.md2safehtml(artist.note) %></td>
        <td class="cell_action_show"><%= link_to t("tables.Show"), artist %></td>
        <% if can? :update, artist %>
          <td class="editor_only cell_action"><%= link_to 'Edit', edit_artist_path(artist) %></td>
        <% end %>
        <td class="cell_note_engage_how"><%= ModuleRedcarpetAux.md2safehtml(compile_engage_notes(artist, music)) %></td>
        <% if can? :update, artist %>
          <td class="editor_only text-center cell_action cell_edit_engage"><%= link_to 'Edit', edit_engage_multi_how_path(engage) %></td> <%# "engage" is set above %>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<% if can? :create, Artist %>
  <p><span class=" editor_only">Add a <span class="lead"><%= link_to "new Artist-Engage", new_engage_path(music_id: music.id) %></span>.</span></p>
<% end %>

app/views/musics/edit.html.erb
<h1>Editing Music: <%= @music.title %></h1>

<%= render 'form', music: @music %>
<hr>
<%= link_to 'Show this Music', @music %> |
<%= link_to 'Back to Index', musics_path %>

app/views/musics/index.html.erb
<h1><%= t("Music").pluralize(8, I18n.locale) %> <%= @artist_title ? "to newly associate with Artist "+@artist_title : '' %></h1>
<% artist_id = (@artist ? @artist.id : nil) %>

<%= datagrid_form_with model: @grid, method: :get, url: musics_path %>

<%= paginate(@grid.assets) %>
<%= datagrid_table @grid %>
<%= paginate(@grid.assets) %>

<%= render "layouts/grid_table_tail", klass: Music %>

<% if can? :create, Music %>
 <div class="button_new">
  <% if @artist_title %>
    <%= link_to 'Create a new music associated with '+@artist_title, new_music_path(music: {artist_id: artist_id}) %> <%# button_to does not work with a GET parameter... %>
  <% else %>
    <%= button_to 'Create New Music', new_music_path, method: :get %>
  <% end %>
 </div>
<% end %>

app/views/musics/show.html.erb
<h1><%= t(:Music) %>: <%= @music.title_or_alt_tuple_str("[", "]", langcode: I18n.locale) %> (by <%= artist=@music.most_significant_artist; artist ? link_to(artist.title_or_alt(prefer_alt: false, langcode: I18n.locale, lang_fallback_option: :either, str_fallback: "", article_to_head: true), artist, title: "the guessed most significant artist") : 'Unknown' %><%= l(Date.new(@music.year), format: :year_comma) if @music.year %>) <%= h1_note_editor_only(@music, method: :show) %></h1>

<hr>
<section id="sec_primary">
<%= render partial: 'layouts/all_registered_translations', locals: {model: @music, add_buttons: true} %>
<hr>

 <section id="sec_primary_show">
<div id="<%= dom_id @music %>">
<dl>
  <% if (can_update=can?(:update, Music)) %>
    <div class="editor_only">
      <dt>pID (<%= @music.class.name %>)</dt>
      <dd> <%= @music.id %></dd>
    </div>
  <% end %>

  <div>
  <dt class="item_year" title="Year"><strong><%= t(:Year_Title) %>:</strong></dt>
    <dd class="item_year"><%= @music.year %></dd>
  </div>
  <div>
  <dt class="item_place"> <%= t("tables.place_country", default: "Place (Country)") %>:</dt>
    <dd class="item_place"><%= show_pref_place_country(@music.place) %>  <%# defined in places_helper.rb %>
      <%= editor_only_safe_html(@music, method: :edit, tag: "span") do %> <%# defined in application_helper.rb %>
        <%= html_consistent_or_inconsistent(!@music.world_to_update_to_japan?, postfix: " with Title or lead-Artist's Country (Japan)".html_safe) %>  <%# defined in application_helper.rb %>
      <% end %>
      </dd>
  </div>
  <div>
  <dt class="item_genre" title="Genre"><strong><%= s=t(:Genre); can?(:update, Genre) ? (link_to s, genres_url) : s %>:</strong></dt>
    <dd class="item_genre"><%= sprintf('%s [%s]', *(%w(ja en).map{|i| @music.genre.title(langcode: i) || ''})) rescue 'nil' %></dd>
  </div>
  <div>
  <dt title="HaramiVid"><strong><%= link_to t(:HaramiVid), "#sec_harami_vids_for" %>:</strong></dt>
    <dd><%= t(:times, count: @music.harami_vids.count) %></dd>
  </div>
  <%= render partial: 'layouts/show_note_memo_timestamps', locals: {model: @music, model4ability: can_update} %>
</dl>
</div>
 </section> <%# closing section id="sec_primary_show" %>

   <%= turbo_frame_tag "musics_anchorings_"+dom_id(@music) do %>
     <%= render partial: 'layouts/index_anchorings', locals: {record: @music} %>
   <% end %>

<%= render partial: 'layouts/link_merge_destroy', locals: {model: @music,  is_to_edit: false} %>
</section> <%# closing section id="sec_primary" %>

<hr>

<section id="sec_artists_by">
<%= render partial: 'artists_table', locals: {music: @music, add_buttons: true} %>
</section>

<hr>

<section id="sec_harami_vids_for">
<h3><%= t("show.h2_harami_vid").pluralize(@music.harami_vids.count, I18n.locale) %><%= t("show.h2_for") %><%= t("Music") %>: <%= @music.title_or_alt %></h3>
<%= render partial: 'layouts/harami_vids_index', locals: {harami_vids: @music.harami_vids.order("harami_vids.release_date" => :desc), music: @music} %>
</section>

<% if can? :read, Harami1129 %>
  <hr>
  <section id="sec_harami1129s_for">
    <h3>Harami1129s<%= t("show.h2_for") %><%= t("Music") %>: <%= @music.title_or_alt(langcode: I18n.locale, lang_fallback_option: :either, article_to_head: true) %></h3>
    <%= render partial: 'layouts/harami1129s_table', locals: {harami1129s: @music.harami1129s} %>
  </section>
<% end %>

<hr>

<%= link_to t("layouts.back_to_index"), musics_path %>